version: '3.4'
services:
  website:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: focus-app
    environment:
      NODE_ENV: production
    ports:
      - 80:80
